version: '3.1'

services:
  app:
    container_name: recipes_app
    build: .
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - recipe
  db:
    container_name: recipes_db
    image: postgres:15-bullseye
    restart: always
    environment:
    - POSTGRES_DB=recipes_api
    - POSTGRES_USER=recipe
    - POSTGRES_PASSWORD=recipe
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}']
      interval: 1s
      timeout: 5s
      retries: 10
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - recipe

volumes:
  pgdata:

networks:
  recipe:
    name: recipe
    driver: bridge